spring:
  datasource:
    url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/master.yaml
  application:
    name: Resource Booking
    description: Этот API предоставляет возможность управлять бронированием ресурсов. Включает возможности для создания, редактирования и удаления бронирований, а также интеграцию с платежными системами для обработки оплаты.
    version: 1.0
    limitDaysToBook: 30
  jpa:
    hibernate:
      ddl-auto: validate
server:
  port: 8089
logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    org.springframework: INFO
    com.zaxxer.hikari: ERROR
    liquibase: ERROR
    org.springframework.security: ERROR
  logback:
    rollingpolicy:
      max-history: 5
      max-file-size: 10MB
